#Villager Info

#Information Toggles
#True to enable the information to display when requested, false for it not to display
baby-age: true
profession: true
job-site: true
last-worked: true
bed-location: true
last-slept: true
inventory: true
restocks: true
reputation: true
highlight-workstation: true
sound-toggle: true
#Sound must be from this list https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
sound: BLOCK_AMETHYST_BLOCK_BREAK
#Length of time to highlight the villager's workstation (if enabled)
highlight-time: 10
