#Villager Info

#Information Toggles
#True to enable the information to display when requested, false for it not to display
Profession: true

Job Site: true

Last Worked: true

Number of Restocks: true

Bed Location: true

Last Slept: true

Villager Inventory Contents: true

#Messages
#Customize the messages you want displayed to the user

Prefix: "&#3256a8&l[&#4dd5ffVillager Info&#3256a8&l]"

Toggle On: "&aVillager Info Toggled &nON"

Toggle Off: "&cVillager Info Toggled &nOFF"

No Permission: "&cYou don't have permission to use this command!"

No Command: "&cNo subcommand by that name!"

Config Reloaded: "&6VillagerInfo Config Reloaded!"
