#Villager Info

#Information Toggles
#True to enable the information to display when requested, false for it not to display
Profession: true

Job Site: true

Last Worked: true

Number of Restocks: true # This only works on Paper or Paper Forks.

Bed Location: true

Last Slept: true

Villager Inventory Contents: true

#Messages
#Customize the messages you want displayed to the user

Prefix: "&#3256a8&l[&#4dd5ffVillager Info&#3256a8&l]"

Toggle On: "&aVillager Info Toggled &nON"

Toggle Off: "&cVillager Info Toggled &nOFF"

No Permission: "&cYou don't have permission to use this command!"

No Permission Vill Toggle: "&cYou are missing the permission villagerinfo.use"

No Command: "&cNo subcommand by that name!"

Config Reloaded: "&6VillagerInfo Config Reloaded!"

#Other
#Whether sounds should be enabled at all

Sound Toggle: true

#Sound must be from this list https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html

Sound: BLOCK_AMETHYST_BLOCK_BREAK