name: VillagerInfo
author: IllogicalSong (Special thanks to Peashooter101)
description: Easier access to information from villager's brains generally only accessable through the /data command.
version: '${project.version}'
main: adhdmc.villagerinfo.VillagerInfo
api-version: 1.19
commands:
  vill:
    description: base command for VillagerInfo
    permission: villagerinfo.use
permissions:
  villagerinfo.reload:
    description: reload VillagerInfo config
  villagerinfo.use:
    description: get the villager information by shift-right-clicking on a villager
  villagerinfo.toggle:
    description: allows toggling functionality on/off