name: VillagerInfo
authors:
  - Rhythmic
  - Peashooter101
description: Easier access to information from villager's brains generally only accessable through the /data command.
version: '${project.version}'
main: adhdmc.villagerinfo.VillagerInfo
api-version: 1.19
website: https://github.com/ADHDMC/VillagerInfo
commands:
  vill:
    description: base command for VillagerInfo
    permission: villagerinfo.use
permissions:
  villagerinfo.reload:
    description: reload VillagerInfo config
    default: op
  villagerinfo.use:
    description: get the villager information by crouch-right-clicking on a villager
    default: op
  villagerinfo.toggle:
    description: allows toggling functionality on/off
    default: op
