name: VillagerInfo
author: IllogicalSong (Special thanks to Peashooter101)
description: Easy access to information from villager's brains generally only accessable through the /data command.
version: '1.2'
main: adhdmc.villagerinfo.VillagerInfo
api-version: 1.13
commands:
  vill:
    description: ""
    usage: ""
    permission: ""
permissions:
  villagerinfo.reload:
    description: reload plugin config
  villagerinfo.use:
    description: get the villager info from shift-right-clicking on a villager
  villagerinfo.toggle:
    description: allows toggling on/off