name: VillagerInfo
version: '${project.version}'
main: adhdmc.villagerinfo.VillagerInfo
api-version: 1.17
commands:
  vill:
    description: ""
    usage: ""
    permission: ""
permissions:
  villagerinfo.reload:
    description: reload plugin config
  villagerinfo.use:
    description: get the villager info from shift-right-clicking on a villager
  villagerinfo.toggle:
    description: allows toggling on/off